title: "THE NHL API Project"
author: "Mohsen Dehghani"
description: "Mila - Quebec Artificial Intelligence Institute"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false       # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Home Change"}#, icon:"home"}
  - {file: "README.md", title: "About"}#, icon : "address-card"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:mohsen.dehghani@mila.quebec"}
  - {title: Github, icon: github, url: "https://github.com/modeha"}
  - {title: Subscribe, icon: rss, url: "https://modeha.github.io/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
